{"errors":[{"message":"request to https://api.datacite.org/client-api/graphql failed, reason: connect ETIMEDOUT 54.76.253.126:443","extensions":{"code":"INTERNAL_SERVER_ERROR"}}],"data":null}
